services:
  db:
    container_name: db
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/x86_64
    tty: true
    ports:
      - 3306:3306
    env_file:
      - ./.db_env
    volumes:
      - type: volume
        source: mysql-data
        target: /var/lib/mysql
volumes:
  mysql-data:
    name: mysql-volume